# See list of defaults here: https://docs.rubocop.org/rubocop/index.html

require:
  - rubocop-performance
  - rubocop-minitest
  - rubocop-rake

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

# ------------------------------------------------------------------------------
# DEPARTMENT LAYOUT
# ------------------------------------------------------------------------------

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent # default: special_inside_parentheses

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent # default: special_inside_parentheses

Layout/LineLength:
  Max: 80 # default: 120

# ------------------------------------------------------------------------------
# DEPARTMENT METRICS
# ------------------------------------------------------------------------------

Metrics/AbcSize:
  Max: 20 # default: 17

Metrics/BlockLength:
  Exclude:
    - file_structure.gemspec
    - test/**/test_*.rb

Metrics/ClassLength:
  Exclude:
    - test/**/test_*.rb

Metrics/MethodLength:
  Max: 15 # default: 10

# ------------------------------------------------------------------------------
# DEPARTMENT STYLE
# ------------------------------------------------------------------------------

Style/Documentation:
  Enabled: false # default: true
